/**
 * L'Arena: i livelli di PLINTO dal 201 al 300.
 *
 * QUESTO FILE E' GENERATO da tools/genera-quadri.mjs (QUADRI_OPERA=arena).
 * Modificarlo a mano funziona, ma la prossima rigenerazione cancella le modifiche: meglio
 * cambiare il progetto nel generatore, dove stanno gli atti, i motivi delle griglie e la
 * curva. Le opere si mettono in fila in src/config/quadri.js.
 *
 * I BERSAGLI NON SONO INVENTATI. Ogni livello e' stato giocato 16 volte dal
 * giocatore artificiale senza obiettivo, e il bersaglio e' un percentile di quanto ha
 * effettivamente ottenuto in quel livello, con quella griglia e quel tetto di mosse.
 * Il percentile sale lungo il percorso: e' cosi' che cresce la difficolta'.
 * La prima stesura, scritta a mano, chiedeva 1500 punti dove se ne facevano 325.
 *
 * TARATI NELLA MODALITA' "anteprima", cioe' la stessa in cui i Quadri si giocano.
 * Non e' un dettaglio: vedere la terna successiva cambia l'ordine in cui il generatore
 * legge la griglia, quindi lo stesso seme produce un'altra partita. Un bersaglio tarato
 * senza anteprima e giocato con l'anteprima e' un bersaglio misurato su un livello che
 * non esiste. MODALITA_TARATURA qui sotto lo dichiara, e un test controlla che
 * coincida con la modalita' davvero giocata.
 *
 * Le griglie iniziali sono verificate: nessuna contiene una riga, una colonna o un
 * quadrante gia' completi, e nessuna e' fatta di celle isolate (un motivo del genere
 * rende il livello ingiocabile, ed e' un errore gia' commesso e gia' misurato).
 */

/** Motivi delle griglie di ostacoli, condivisi fra piu' Quadri. */
const MOTIVI = {
  mattoneCentrale: [
    '.........',
    '.........',
    '.........',
    '.........',
    '....R....',
    '.........',
    '.........',
    '.........',
    '.........',
  ].join('\n'),
  quattroMattoni: [
    '.........',
    '.r.....R.',
    '.........',
    '.........',
    '.........',
    '.........',
    '.........',
    '.R.....r.',
    '.........',
  ].join('\n'),
  filaMattoni: [
    '.........',
    '.........',
    '.........',
    '.........',
    '.R..R..R.',
    '.........',
    '.........',
    '.........',
    '.........',
  ].join('\n'),
  croceMattoni: [
    '.........',
    '....R....',
    '.........',
    '.........',
    '.R..R..R.',
    '.........',
    '.........',
    '....R....',
    '.........',
  ].join('\n'),
  portali: [
    '....R....',
    '.........',
    '..R...R..',
    '.........',
    'R.......R',
    '.........',
    '..R...R..',
    '.........',
    '....R....',
  ].join('\n'),
  diagonaleMattoni: [
    'R........',
    '.R.......',
    '..R......',
    '...R.....',
    '....R....',
    '.....R...',
    '......R..',
    '.......R.',
    '........R',
  ].join('\n'),
  anelloMattoni: [
    '.........',
    '...R.R...',
    '.........',
    '.R.....R.',
    '.........',
    '.R.....R.',
    '.........',
    '...R.R...',
    '.........',
  ].join('\n'),
  coppie: [
    '.........',
    '.RR...RR.',
    '.........',
    '.........',
    '.........',
    '.........',
    '.........',
    '.RR...RR.',
    '.........',
  ].join('\n'),
  gradinata: [
    '##.....##',
    '#R.....R#',
    '.........',
    '.........',
    '.........',
    '.........',
    '.........',
    '#R.....R#',
    '##.....##',
  ].join('\n'),
  cerchio: [
    '...###...',
    '..R...R..',
    '.R.....R.',
    '#.......#',
    '#...R...#',
    '#.......#',
    '.R.....R.',
    '..R...R..',
    '...###...',
  ].join('\n'),
  spalti: [
    'RR.....RR',
    'R.......R',
    '.........',
    '.........',
    '.........',
    '.........',
    '.........',
    'R.......R',
    'RR.....RR',
  ].join('\n'),
  portico: [
    '.#.#.#.#.',
    '.R.R.R.R.',
    '.........',
    '.........',
    '.........',
    '.........',
    '.........',
    '.R.R.R.R.',
    '.#.#.#.#.',
  ].join('\n'),
  volta: [
    '...RRR...',
    '.R.....R.',
    'R.......R',
    'R.......R',
    '.........',
    'R.......R',
    'R.......R',
    '.R.....R.',
    '...RRR...',
  ].join('\n'),
  velario: [
    'R.#.R.#.R',
    '.........',
    '#.......#',
    '.........',
    'R...R...R',
    '.........',
    '#.......#',
    '.........',
    'R.#.R.#.R',
  ].join('\n'),
  tribuna: [
    '##R#.#R##',
    '.R.....R.',
    '.........',
    '.........',
    '....R....',
    '.........',
    '.........',
    '.R.....R.',
    '##R#.#R##',
  ].join('\n'),
  anfiteatro: [
    '.RRR.RRR.',
    'R.......R',
    'R.......R',
    'R.......R',
    '.........',
    'R.......R',
    'R.......R',
    'R.......R',
    '.RRR.RRR.',
  ].join('\n'),
};

/** La modalita' di gioco in cui questi bersagli sono stati misurati. */
export const MODALITA_TARATURA = 'anteprima';

export const QUADRI = [
  { numero: 201, nome: 'righe201', atto: "tracciato", obiettivi: [{ tipo: 'righe', quanti: 3 }], maxMosse: 16,
    griglia: MOTIVI.mattoneCentrale, },
  { numero: 202, nome: 'mattoni202', atto: "tracciato", obiettivi: [{ tipo: 'demolizioni', quanti: 3 }], maxMosse: 16,
    griglia: MOTIVI.quattroMattoni, },
  { numero: 203, nome: 'colonne203', atto: "tracciato", obiettivi: [{ tipo: 'colonne', quanti: 3 }], maxMosse: 15,
    griglia: MOTIVI.filaMattoni, },
  { numero: 204, nome: 'gruppi204', atto: "tracciato", obiettivi: [{ tipo: 'gruppi', quanti: 4 }], maxMosse: 17,
    griglia: MOTIVI.croceMattoni, },
  { numero: 205, nome: 'righe205', atto: "tracciato", obiettivi: [{ tipo: 'righe', quanti: 4 }], maxMosse: 14,
    griglia: MOTIVI.mattoneCentrale, },
  { numero: 206, nome: 'mattoni206', atto: "tracciato", obiettivi: [{ tipo: 'demolizioni', quanti: 3 }], maxMosse: 16,
    griglia: MOTIVI.quattroMattoni, },
  { numero: 207, nome: 'colonne207', atto: "tracciato", obiettivi: [{ tipo: 'colonne', quanti: 4 }], maxMosse: 18,
    griglia: MOTIVI.filaMattoni, },
  { numero: 208, nome: 'gruppi208', atto: "tracciato", obiettivi: [{ tipo: 'gruppi', quanti: 5 }], maxMosse: 15,
    griglia: MOTIVI.croceMattoni, },
  { numero: 209, nome: 'righe209', atto: "tracciato", obiettivi: [{ tipo: 'righe', quanti: 3 }], maxMosse: 17,
    griglia: MOTIVI.mattoneCentrale, },
  { numero: 210, nome: 'mattoni210', atto: "tracciato", obiettivi: [{ tipo: 'demolizioni', quanti: 3 }], maxMosse: 18,
    griglia: MOTIVI.quattroMattoni, },
  { numero: 211, nome: 'gruppi211', atto: "ingressi", obiettivi: [{ tipo: 'gruppi', quanti: 6 }], maxMosse: 19,
    griglia: MOTIVI.portali, },
  { numero: 212, nome: 'mattoni212', atto: "ingressi", obiettivi: [{ tipo: 'demolizioni', quanti: 3 }], maxMosse: 22,
    griglia: MOTIVI.diagonaleMattoni, },
  { numero: 213, nome: 'quadranti213', atto: "ingressi", obiettivi: [{ tipo: 'quadranti', quanti: 5 }], maxMosse: 18,
    griglia: MOTIVI.anelloMattoni, },
  { numero: 214, nome: 'righe214', atto: "ingressi", obiettivi: [{ tipo: 'righe', quanti: 6 }], maxMosse: 21,
    griglia: MOTIVI.coppie, },
  { numero: 215, nome: 'catena215', atto: "ingressi", obiettivi: [{ tipo: 'catena', quanti: 1 }], maxMosse: 8,
    griglia: MOTIVI.portali, },
  { numero: 216, nome: 'gruppi216', atto: "ingressi", obiettivi: [{ tipo: 'gruppi', quanti: 7 }], maxMosse: 19,
    griglia: MOTIVI.diagonaleMattoni, },
  { numero: 217, nome: 'mattoni217', atto: "ingressi", obiettivi: [{ tipo: 'demolizioni', quanti: 4 }], maxMosse: 22,
    griglia: MOTIVI.anelloMattoni, },
  { numero: 218, nome: 'quadranti218', atto: "ingressi", obiettivi: [{ tipo: 'quadranti', quanti: 6 }], maxMosse: 18,
    griglia: MOTIVI.coppie, },
  { numero: 219, nome: 'righe219', atto: "ingressi", obiettivi: [{ tipo: 'righe', quanti: 6 }], maxMosse: 21,
    griglia: MOTIVI.portali, },
  { numero: 220, nome: 'catena220', atto: "ingressi", obiettivi: [{ tipo: 'catena', quanti: 3 }], maxMosse: 15,
    griglia: MOTIVI.diagonaleMattoni, },
  { numero: 221, nome: 'gruppi221', atto: "ingressi", obiettivi: [{ tipo: 'gruppi', quanti: 7 }], maxMosse: 21,
    griglia: MOTIVI.anelloMattoni, },
  { numero: 222, nome: 'mattoni222', atto: "ingressi", obiettivi: [{ tipo: 'demolizioni', quanti: 5 }], maxMosse: 22,
    griglia: MOTIVI.coppie, },
  { numero: 223, nome: 'quadranti223', atto: "ingressi", obiettivi: [{ tipo: 'quadranti', quanti: 6 }], maxMosse: 18,
    griglia: MOTIVI.portali, },
  { numero: 224, nome: 'righe224', atto: "ingressi", obiettivi: [{ tipo: 'righe', quanti: 5 }], maxMosse: 21,
    griglia: MOTIVI.diagonaleMattoni, },
  { numero: 225, nome: 'mattoni225', atto: "gradinate", obiettivi: [{ tipo: 'demolizioni', quanti: 4 }], maxMosse: 12,
    griglia: MOTIVI.gradinata, },
  { numero: 226, nome: 'gruppi226', atto: "gradinate", obiettivi: [{ tipo: 'gruppi', quanti: 8 }], maxMosse: 20,
    griglia: MOTIVI.cerchio, },
  { numero: 227, nome: 'quadranti227', atto: "gradinate", obiettivi: [{ tipo: 'quadranti', quanti: 8 }], maxMosse: 26,
    griglia: MOTIVI.spalti, },
  { numero: 228, nome: 'colonne228', atto: "gradinate", obiettivi: [{ tipo: 'colonne', quanti: 6 }], maxMosse: 21,
    griglia: MOTIVI.anelloMattoni, },
  { numero: 229, nome: 'catena229', atto: "gradinate", obiettivi: [{ tipo: 'catena', quanti: 4 }], maxMosse: 24,
    griglia: MOTIVI.gradinata, },
  { numero: 230, nome: 'intrecci230', atto: "gradinate", obiettivi: [{ tipo: 'intrecci', quanti: 2 }], maxMosse: 18,
    griglia: MOTIVI.cerchio, },
  { numero: 231, nome: 'mattoni231', atto: "gradinate", obiettivi: [{ tipo: 'demolizioni', quanti: 8 }], maxMosse: 14,
    griglia: MOTIVI.spalti, },
  { numero: 232, nome: 'gruppi232', atto: "gradinate", obiettivi: [{ tipo: 'gruppi', quanti: 9 }], maxMosse: 26,
    griglia: MOTIVI.anelloMattoni, },
  { numero: 233, nome: 'quadranti233', atto: "gradinate", obiettivi: [{ tipo: 'quadranti', quanti: 8 }], maxMosse: 21,
    griglia: MOTIVI.gradinata, },
  { numero: 234, nome: 'colonne234', atto: "gradinate", obiettivi: [{ tipo: 'colonne', quanti: 7 }], maxMosse: 24,
    griglia: MOTIVI.cerchio, },
  { numero: 235, nome: 'catena235', atto: "gradinate", obiettivi: [{ tipo: 'catena', quanti: 5 }], maxMosse: 25,
    griglia: MOTIVI.spalti, },
  { numero: 236, nome: 'intrecci236', atto: "gradinate", obiettivi: [{ tipo: 'intrecci', quanti: 1 }], maxMosse: 8,
    griglia: MOTIVI.anelloMattoni, },
  { numero: 237, nome: 'mattoni237', atto: "gradinate", obiettivi: [{ tipo: 'demolizioni', quanti: 4 }], maxMosse: 11,
    griglia: MOTIVI.gradinata, },
  { numero: 238, nome: 'gruppi238', atto: "gradinate", obiettivi: [{ tipo: 'gruppi', quanti: 8 }], maxMosse: 21,
    griglia: MOTIVI.cerchio, },
  { numero: 239, nome: 'quadranti239', atto: "gradinate", obiettivi: [{ tipo: 'quadranti', quanti: 9 }], maxMosse: 24,
    griglia: MOTIVI.spalti, },
  { numero: 240, nome: 'colonne240', atto: "gradinate", obiettivi: [{ tipo: 'colonne', quanti: 7 }], maxMosse: 23,
    griglia: MOTIVI.anelloMattoni, },
  { numero: 241, nome: 'mattoni241', atto: "portici", obiettivi: [{ tipo: 'demolizioni', quanti: 5 }], maxMosse: 22,
    griglia: MOTIVI.portico, },
  { numero: 242, nome: 'catena242', atto: "portici", obiettivi: [{ tipo: 'catena', quanti: 4 }], maxMosse: 26,
    griglia: MOTIVI.cerchio, },
  { numero: 243, nome: 'intrecci243', atto: "portici", obiettivi: [{ tipo: 'intrecci', quanti: 1 }], maxMosse: 20,
    griglia: MOTIVI.spalti, },
  { numero: 244, nome: 'gruppimattoni244', atto: "portici", obiettivi: [{ tipo: 'gruppi', quanti: 8 }, { tipo: 'demolizioni', quanti: 4 }], maxMosse: 20,
    griglia: MOTIVI.gradinata, },
  { numero: 245, nome: 'punti245', atto: "portici", obiettivi: [{ tipo: 'punteggio', quanti: 200 }], maxMosse: 18,
    griglia: MOTIVI.portali, },
  { numero: 246, nome: 'mattoni246', atto: "portici", obiettivi: [{ tipo: 'demolizioni', quanti: 6 }], maxMosse: 24,
    griglia: MOTIVI.portico, },
  { numero: 247, nome: 'catena247', atto: "portici", obiettivi: [{ tipo: 'catena', quanti: 4 }], maxMosse: 26,
    griglia: MOTIVI.cerchio, },
  { numero: 248, nome: 'intreccipunti248', atto: "portici", obiettivi: [{ tipo: 'intrecci', quanti: 1 }, { tipo: 'punteggio', quanti: 275 }], maxMosse: 17,
    griglia: MOTIVI.spalti, },
  { numero: 249, nome: 'gruppi249', atto: "portici", obiettivi: [{ tipo: 'gruppi', quanti: 9 }], maxMosse: 21,
    griglia: MOTIVI.gradinata, },
  { numero: 250, nome: 'punti250', atto: "portici", obiettivi: [{ tipo: 'punteggio', quanti: 225 }], maxMosse: 20,
    griglia: MOTIVI.portali, },
  { numero: 251, nome: 'mattoni251', atto: "portici", obiettivi: [{ tipo: 'demolizioni', quanti: 7 }], maxMosse: 24,
    griglia: MOTIVI.portico, },
  { numero: 252, nome: 'catenagruppi252', atto: "portici", obiettivi: [{ tipo: 'catena', quanti: 3 }, { tipo: 'gruppi', quanti: 9 }], maxMosse: 26,
    griglia: MOTIVI.cerchio, },
  { numero: 253, nome: 'intrecci253', atto: "portici", obiettivi: [{ tipo: 'intrecci', quanti: 3 }], maxMosse: 26,
    griglia: MOTIVI.spalti, },
  { numero: 254, nome: 'gruppi254', atto: "portici", obiettivi: [{ tipo: 'gruppi', quanti: 10 }], maxMosse: 24,
    griglia: MOTIVI.gradinata, },
  { numero: 255, nome: 'punti255', atto: "portici", obiettivi: [{ tipo: 'punteggio', quanti: 250 }], maxMosse: 19,
    griglia: MOTIVI.portali, },
  { numero: 256, nome: 'mattoniintrecci256', atto: "portici", obiettivi: [{ tipo: 'demolizioni', quanti: 4 }, { tipo: 'intrecci', quanti: 1 }], maxMosse: 22,
    griglia: MOTIVI.portico, },
  { numero: 257, nome: 'catena257', atto: "portici", obiettivi: [{ tipo: 'catena', quanti: 4 }], maxMosse: 26,
    griglia: MOTIVI.cerchio, },
  { numero: 258, nome: 'intrecci258', atto: "portici", obiettivi: [{ tipo: 'intrecci', quanti: 3 }], maxMosse: 25,
    griglia: MOTIVI.spalti, },
  { numero: 259, nome: 'mattoni259', atto: "volte", obiettivi: [{ tipo: 'demolizioni', quanti: 11 }], maxMosse: 28,
    griglia: MOTIVI.volta, },
  { numero: 260, nome: 'punti260', atto: "volte", obiettivi: [{ tipo: 'punteggio', quanti: 300 }], maxMosse: 17,
    griglia: MOTIVI.portico, },
  { numero: 261, nome: 'intrecci261', atto: "volte", obiettivi: [{ tipo: 'intrecci', quanti: 2 }], maxMosse: 25,
    griglia: MOTIVI.velario, },
  { numero: 262, nome: 'gruppirighe262', atto: "volte", obiettivi: [{ tipo: 'gruppi', quanti: 12 }, { tipo: 'righe', quanti: 10 }], maxMosse: 29,
    griglia: MOTIVI.spalti, },
  { numero: 263, nome: 'celle263', atto: "volte", obiettivi: [{ tipo: 'celle', quanti: 72 }], maxMosse: 21,
    griglia: MOTIVI.cerchio, },
  { numero: 264, nome: 'righe264', atto: "volte", obiettivi: [{ tipo: 'righe', quanti: 8 }], maxMosse: 21,
    griglia: MOTIVI.volta, },
  { numero: 265, nome: 'mattoni265', atto: "volte", obiettivi: [{ tipo: 'demolizioni', quanti: 7 }], maxMosse: 24,
    griglia: MOTIVI.portico, },
  { numero: 266, nome: 'puntigruppi266', atto: "volte", obiettivi: [{ tipo: 'punteggio', quanti: 325 }, { tipo: 'gruppi', quanti: 8 }], maxMosse: 22,
    griglia: MOTIVI.velario, },
  { numero: 267, nome: 'intrecci267', atto: "volte", obiettivi: [{ tipo: 'intrecci', quanti: 3 }], maxMosse: 30,
    griglia: MOTIVI.spalti, },
  { numero: 268, nome: 'gruppi268', atto: "volte", obiettivi: [{ tipo: 'gruppi', quanti: 11 }], maxMosse: 26,
    griglia: MOTIVI.cerchio, },
  { numero: 269, nome: 'celle269', atto: "volte", obiettivi: [{ tipo: 'celle', quanti: 93 }], maxMosse: 26,
    griglia: MOTIVI.volta, },
  { numero: 270, nome: 'righepunti270', atto: "volte", obiettivi: [{ tipo: 'righe', quanti: 3 }, { tipo: 'punteggio', quanti: 225 }], maxMosse: 20,
    griglia: MOTIVI.portico, },
  { numero: 271, nome: 'mattoni271', atto: "volte", obiettivi: [{ tipo: 'demolizioni', quanti: 7 }], maxMosse: 25,
    griglia: MOTIVI.velario, },
  { numero: 272, nome: 'punti272', atto: "volte", obiettivi: [{ tipo: 'punteggio', quanti: 500 }], maxMosse: 30,
    griglia: MOTIVI.spalti, },
  { numero: 273, nome: 'intrecci273', atto: "volte", obiettivi: [{ tipo: 'intrecci', quanti: 3 }], maxMosse: 17,
    griglia: MOTIVI.cerchio, },
  { numero: 274, nome: 'gruppiintrecci274', atto: "volte", obiettivi: [{ tipo: 'gruppi', quanti: 11 }, { tipo: 'intrecci', quanti: 2 }], maxMosse: 25,
    griglia: MOTIVI.volta, },
  { numero: 275, nome: 'celle275', atto: "volte", obiettivi: [{ tipo: 'celle', quanti: 70 }], maxMosse: 22,
    griglia: MOTIVI.portico, },
  { numero: 276, nome: 'righe276', atto: "volte", obiettivi: [{ tipo: 'righe', quanti: 9 }], maxMosse: 26,
    griglia: MOTIVI.velario, },
  { numero: 277, nome: 'mattoni277', atto: "velario", obiettivi: [{ tipo: 'demolizioni', quanti: 8 }], maxMosse: 32,
    griglia: MOTIVI.velario, },
  { numero: 278, nome: 'punti278', atto: "velario", obiettivi: [{ tipo: 'punteggio', quanti: 525 }], maxMosse: 29,
    griglia: MOTIVI.tribuna, },
  { numero: 279, nome: 'catena279', atto: "velario", obiettivi: [{ tipo: 'catena', quanti: 7 }], maxMosse: 30,
    griglia: MOTIVI.volta, },
  { numero: 280, nome: 'cellegruppi280', atto: "velario", obiettivi: [{ tipo: 'celle', quanti: 66 }, { tipo: 'gruppi', quanti: 8 }], maxMosse: 22,
    griglia: MOTIVI.portico, },
  { numero: 281, nome: 'intrecci281', atto: "velario", obiettivi: [{ tipo: 'intrecci', quanti: 3 }], maxMosse: 24,
    griglia: MOTIVI.spalti, },
  { numero: 282, nome: 'gruppi282', atto: "velario", obiettivi: [{ tipo: 'gruppi', quanti: 13 }], maxMosse: 29,
    griglia: MOTIVI.velario, },
  { numero: 283, nome: 'mattoni283', atto: "velario", obiettivi: [{ tipo: 'demolizioni', quanti: 8 }], maxMosse: 30,
    griglia: MOTIVI.tribuna, },
  { numero: 284, nome: 'punticelle284', atto: "velario", obiettivi: [{ tipo: 'punteggio', quanti: 475 }, { tipo: 'celle', quanti: 87 }], maxMosse: 30,
    griglia: MOTIVI.volta, },
  { numero: 285, nome: 'catena285', atto: "velario", obiettivi: [{ tipo: 'catena', quanti: 4 }], maxMosse: 22,
    griglia: MOTIVI.portico, },
  { numero: 286, nome: 'celle286', atto: "velario", obiettivi: [{ tipo: 'celle', quanti: 84 }], maxMosse: 26,
    griglia: MOTIVI.spalti, },
  { numero: 287, nome: 'intrecci287', atto: "velario", obiettivi: [{ tipo: 'intrecci', quanti: 4 }], maxMosse: 32,
    griglia: MOTIVI.velario, },
  { numero: 288, nome: 'gruppi288', atto: "velario", obiettivi: [{ tipo: 'gruppi', quanti: 13 }], maxMosse: 29,
    griglia: MOTIVI.tribuna, },
  { numero: 289, nome: 'mattoni289', atto: "velario", obiettivi: [{ tipo: 'demolizioni', quanti: 12 }], maxMosse: 30,
    griglia: MOTIVI.volta, },
  { numero: 290, nome: 'punti290', atto: "velario", obiettivi: [{ tipo: 'punteggio', quanti: 472 }], maxMosse: 25,
    griglia: MOTIVI.portico, },
  { numero: 291, nome: 'catena291', atto: "velario", obiettivi: [{ tipo: 'catena', quanti: 7 }], maxMosse: 26,
    griglia: MOTIVI.spalti, },
  { numero: 292, nome: 'cellemattoni292', atto: "velario", obiettivi: [{ tipo: 'celle', quanti: 93 }, { tipo: 'demolizioni', quanti: 6 }], maxMosse: 32,
    griglia: MOTIVI.velario, },
  { numero: 293, nome: 'mattoni293', atto: "tribuna", obiettivi: [{ tipo: 'demolizioni', quanti: 13 }], maxMosse: 35,
    griglia: MOTIVI.anfiteatro, },
  { numero: 294, nome: 'punti294', atto: "tribuna", obiettivi: [{ tipo: 'punteggio', quanti: 650 }], maxMosse: 35,
    griglia: MOTIVI.tribuna, },
  { numero: 295, nome: 'celle295', atto: "tribuna", obiettivi: [{ tipo: 'celle', quanti: 84 }], maxMosse: 28,
    griglia: MOTIVI.volta, },
  { numero: 296, nome: 'gruppiquadranti296', atto: "tribuna", obiettivi: [{ tipo: 'gruppi', quanti: 12 }, { tipo: 'quadranti', quanti: 9 }], maxMosse: 31,
    griglia: MOTIVI.velario, },
  { numero: 297, nome: 'intrecci297', atto: "tribuna", obiettivi: [{ tipo: 'intrecci', quanti: 6 }], maxMosse: 33,
    griglia: MOTIVI.anfiteatro, },
  { numero: 298, nome: 'quadranti298', atto: "tribuna", obiettivi: [{ tipo: 'quadranti', quanti: 12 }], maxMosse: 29,
    griglia: MOTIVI.tribuna, },
  { numero: 299, nome: 'mattoni299', atto: "tribuna", obiettivi: [{ tipo: 'demolizioni', quanti: 14 }], maxMosse: 33,
    griglia: MOTIVI.volta, },
  { numero: 300, nome: 'puntiquadranti300', atto: "tribuna", obiettivi: [{ tipo: 'punteggio', quanti: 475 }, { tipo: 'quadranti', quanti: 7 }], maxMosse: 26,
    griglia: MOTIVI.velario, },
];

/**
 * Gli atti dell'opera: servono a far vedere dove si e' arrivati.
 *
 * Qui c'e' l'IDENTIFICATIVO, non il nome. Il nome visibile sta nelle traduzioni, sotto
 * "atti.<id>": finche' e' stato scritto qui, in italiano, chi giocava in inglese leggeva
 * "Le basi" e "La vetta" dentro un'interfaccia inglese, e nessuno se n'era accorto perche'
 * i dati generati non passano da nessun controllo sulle traduzioni.
 */
export const ATTI = [
  {
    id: "tracciato",
    da: 201,
    a: 210
  },
  {
    id: "ingressi",
    da: 211,
    a: 224
  },
  {
    id: "gradinate",
    da: 225,
    a: 240
  },
  {
    id: "portici",
    da: 241,
    a: 258
  },
  {
    id: "volte",
    da: 259,
    a: 276
  },
  {
    id: "velario",
    da: 277,
    a: 292
  },
  {
    id: "tribuna",
    da: 293,
    a: 300
  }
];
