/**
 * La Torre: i livelli di PLINTO dal 101 al 200.
 *
 * QUESTO FILE E' GENERATO da tools/genera-quadri.mjs (QUADRI_OPERA=torre).
 * Modificarlo a mano funziona, ma la prossima rigenerazione cancella le modifiche: meglio
 * cambiare il progetto nel generatore, dove stanno gli atti, i motivi delle griglie e la
 * curva. Le opere si mettono in fila in src/config/quadri.js.
 *
 * I BERSAGLI NON SONO INVENTATI. Ogni livello e' stato giocato 16 volte dal
 * giocatore artificiale senza obiettivo, e il bersaglio e' un percentile di quanto ha
 * effettivamente ottenuto in quel livello, con quella griglia e quel tetto di mosse.
 * Il percentile sale lungo il percorso: e' cosi' che cresce la difficolta'.
 * La prima stesura, scritta a mano, chiedeva 1500 punti dove se ne facevano 325.
 *
 * TARATI NELLA MODALITA' "anteprima", cioe' la stessa in cui i Quadri si giocano.
 * Non e' un dettaglio: vedere la terna successiva cambia l'ordine in cui il generatore
 * legge la griglia, quindi lo stesso seme produce un'altra partita. Un bersaglio tarato
 * senza anteprima e giocato con l'anteprima e' un bersaglio misurato su un livello che
 * non esiste. MODALITA_TARATURA qui sotto lo dichiara, e un test controlla che
 * coincida con la modalita' davvero giocata.
 *
 * Le griglie iniziali sono verificate: nessuna contiene una riga, una colonna o un
 * quadrante gia' completi, e nessuna e' fatta di celle isolate (un motivo del genere
 * rende il livello ingiocabile, ed e' un errore gia' commesso e gia' misurato).
 */

/** Motivi delle griglie di ostacoli, condivisi fra piu' Quadri. */
const MOTIVI = {
  masso: [
    '.........',
    '.........',
    '.........',
    '.........',
    '....M....',
    '.........',
    '.........',
    '.........',
    '.........',
  ].join('\n'),
  quattroMassi: [
    '.........',
    '.M.....M.',
    '.........',
    '.........',
    '.........',
    '.........',
    '.........',
    '.M.....M.',
    '.........',
  ].join('\n'),
  filaMassi: [
    '.........',
    '.........',
    '.........',
    '.........',
    '.M..M..M.',
    '.........',
    '.........',
    '.........',
    '.........',
  ].join('\n'),
  croceMassi: [
    '.........',
    '....M....',
    '.........',
    '.........',
    '.M..M..M.',
    '.........',
    '.........',
    '....M....',
    '.........',
  ].join('\n'),
  diagonaleMassi: [
    'M........',
    '.M.......',
    '..M......',
    '...M.....',
    '....M....',
    '.....M...',
    '......M..',
    '.......M.',
    '........M',
  ].join('\n'),
  cuori: [
    '.........',
    '.M..M..M.',
    '.........',
    '.........',
    '.M..M..M.',
    '.........',
    '.........',
    '.M..M..M.',
    '.........',
  ].join('\n'),
  merlatura: [
    'M.M.M.M.M',
    '.........',
    '.........',
    '.........',
    '.........',
    '.........',
    '.........',
    '.........',
    'M.M.M.M.M',
  ].join('\n'),
  murettiMassi: [
    '.........',
    '.MM...MM.',
    '.........',
    '...##....',
    '...##....',
    '.........',
    '.MM...MM.',
    '.........',
    '.........',
  ].join('\n'),
  spirale: [
    'MM.......',
    '.........',
    '...MMM...',
    '...#.....',
    '.#.#.M.#.',
    '.....#...',
    '...MMM...',
    '.........',
    '.......MM',
  ].join('\n'),
  pilastrini: [
    '.........',
    '.M..M..M.',
    '.##...##.',
    '.........',
    '.M..M..M.',
    '.........',
    '.##...##.',
    '.M..M..M.',
    '.........',
  ].join('\n'),
  anello: [
    '.........',
    '.........',
    '..M...M..',
    '...###...',
    '...#.#...',
    '...###...',
    '..M...M..',
    '.........',
    '.........',
  ].join('\n'),
  gradini: [
    'MM.......',
    '.........',
    '..MM.....',
    '..##.....',
    '....MM...',
    '....##...',
    '......MM.',
    '.........',
    '........M',
  ].join('\n'),
  feritoie: [
    'M..M..M..',
    '.........',
    '.........',
    '.##..##..',
    'M..M..M..',
    '.........',
    '.........',
    '..##..##.',
    'M..M..M..',
  ].join('\n'),
  torrette: [
    'MM.....MM',
    'MM.....MM',
    '.........',
    '...#.#...',
    '.........',
    '...#.#...',
    '.........',
    'MM.....MM',
    'MM.....MM',
  ].join('\n'),
  arcate: [
    '.M.M.M.M.',
    '.........',
    '.##...##.',
    '.##...##.',
    '....M....',
    '.##...##.',
    '.##...##.',
    '.........',
    '.M.M.M.M.',
  ].join('\n'),
  colonnato: [
    '.M.....M.',
    '.........',
    '.M.....M.',
    '...###...',
    '.........',
    '...###...',
    '.M.....M.',
    '.........',
    '.M.....M.',
  ].join('\n'),
  crenellature: [
    'M.M.M.M.M',
    '#.#...#.#',
    '.........',
    '.........',
    '...MMM...',
    '.........',
    '.........',
    '#.#...#.#',
    'M.M.M.M.M',
  ].join('\n'),
  fortezza: [
    'MM.....MM',
    'M.......M',
    '...###...',
    '.........',
    '#..M.M..#',
    '.........',
    '...###...',
    'M.......M',
    'MM.....MM',
  ].join('\n'),
  pinnacolo: [
    'M...M...M',
    '.##...##.',
    '.#.....#.',
    '...M.M...',
    'M.......M',
    '...M.M...',
    '.#.....#.',
    '.##...##.',
    'M...M...M',
  ].join('\n'),
  assedioMassi: [
    'MM.....MM',
    'M.......M',
    '.........',
    '#..M.M..#',
    '#.......#',
    '#..M.M..#',
    '.........',
    'M.......M',
    'MM.....MM',
  ].join('\n'),
};

/** La modalita' di gioco in cui questi bersagli sono stati misurati. */
export const MODALITA_TARATURA = 'anteprima';

export const QUADRI = [
  { numero: 101, nome: 'righe101', atto: "basamento", obiettivi: [{ tipo: 'righe', quanti: 2 }], maxMosse: 15,
    griglia: MOTIVI.masso, },
  { numero: 102, nome: 'colonne102', atto: "basamento", obiettivi: [{ tipo: 'colonne', quanti: 4 }], maxMosse: 18,
    griglia: MOTIVI.quattroMassi, },
  { numero: 103, nome: 'quadranti103', atto: "basamento", obiettivi: [{ tipo: 'quadranti', quanti: 3 }], maxMosse: 15,
    griglia: MOTIVI.filaMassi, },
  { numero: 104, nome: 'gruppi104', atto: "basamento", obiettivi: [{ tipo: 'gruppi', quanti: 4 }], maxMosse: 17,
    griglia: MOTIVI.croceMassi, },
  { numero: 105, nome: 'righe105', atto: "basamento", obiettivi: [{ tipo: 'righe', quanti: 3 }], maxMosse: 15,
    griglia: MOTIVI.masso, },
  { numero: 106, nome: 'colonne106', atto: "basamento", obiettivi: [{ tipo: 'colonne', quanti: 4 }], maxMosse: 16,
    griglia: MOTIVI.quattroMassi, },
  { numero: 107, nome: 'quadranti107', atto: "basamento", obiettivi: [{ tipo: 'quadranti', quanti: 4 }], maxMosse: 18,
    griglia: MOTIVI.filaMassi, },
  { numero: 108, nome: 'gruppi108', atto: "basamento", obiettivi: [{ tipo: 'gruppi', quanti: 5 }], maxMosse: 18,
    griglia: MOTIVI.croceMassi, },
  { numero: 109, nome: 'righe109', atto: "basamento", obiettivi: [{ tipo: 'righe', quanti: 4 }], maxMosse: 17,
    griglia: MOTIVI.masso, },
  { numero: 110, nome: 'colonne110', atto: "basamento", obiettivi: [{ tipo: 'colonne', quanti: 4 }], maxMosse: 18,
    griglia: MOTIVI.quattroMassi, },
  { numero: 111, nome: 'gruppi111', atto: "mura", obiettivi: [{ tipo: 'gruppi', quanti: 6 }], maxMosse: 19,
    griglia: MOTIVI.diagonaleMassi, },
  { numero: 112, nome: 'quadranti112', atto: "mura", obiettivi: [{ tipo: 'quadranti', quanti: 5 }], maxMosse: 18,
    griglia: MOTIVI.cuori, },
  { numero: 113, nome: 'righe113', atto: "mura", obiettivi: [{ tipo: 'righe', quanti: 4 }], maxMosse: 19,
    griglia: MOTIVI.merlatura, },
  { numero: 114, nome: 'colonne114', atto: "mura", obiettivi: [{ tipo: 'colonne', quanti: 5 }], maxMosse: 21,
    griglia: MOTIVI.murettiMassi, },
  { numero: 115, nome: 'catena115', atto: "mura", obiettivi: [{ tipo: 'catena', quanti: 2 }], maxMosse: 14,
    griglia: MOTIVI.diagonaleMassi, },
  { numero: 116, nome: 'gruppi116', atto: "mura", obiettivi: [{ tipo: 'gruppi', quanti: 7 }], maxMosse: 22,
    griglia: MOTIVI.cuori, },
  { numero: 117, nome: 'quadranti117', atto: "mura", obiettivi: [{ tipo: 'quadranti', quanti: 6 }], maxMosse: 22,
    griglia: MOTIVI.merlatura, },
  { numero: 118, nome: 'righe118', atto: "mura", obiettivi: [{ tipo: 'righe', quanti: 5 }], maxMosse: 18,
    griglia: MOTIVI.murettiMassi, },
  { numero: 119, nome: 'colonne119', atto: "mura", obiettivi: [{ tipo: 'colonne', quanti: 5 }], maxMosse: 21,
    griglia: MOTIVI.diagonaleMassi, },
  { numero: 120, nome: 'catena120', atto: "mura", obiettivi: [{ tipo: 'catena', quanti: 2 }], maxMosse: 14,
    griglia: MOTIVI.cuori, },
  { numero: 121, nome: 'gruppi121', atto: "mura", obiettivi: [{ tipo: 'gruppi', quanti: 6 }], maxMosse: 21,
    griglia: MOTIVI.merlatura, },
  { numero: 122, nome: 'quadranti122', atto: "mura", obiettivi: [{ tipo: 'quadranti', quanti: 7 }], maxMosse: 22,
    griglia: MOTIVI.murettiMassi, },
  { numero: 123, nome: 'righe123', atto: "mura", obiettivi: [{ tipo: 'righe', quanti: 6 }], maxMosse: 21,
    griglia: MOTIVI.diagonaleMassi, },
  { numero: 124, nome: 'colonne124', atto: "mura", obiettivi: [{ tipo: 'colonne', quanti: 5 }], maxMosse: 21,
    griglia: MOTIVI.cuori, },
  { numero: 125, nome: 'gruppi125', atto: "chiocciola", obiettivi: [{ tipo: 'gruppi', quanti: 7 }], maxMosse: 18,
    griglia: MOTIVI.spirale, },
  { numero: 126, nome: 'quadranti126', atto: "chiocciola", obiettivi: [{ tipo: 'quadranti', quanti: 8 }], maxMosse: 25,
    griglia: MOTIVI.pilastrini, },
  { numero: 127, nome: 'righe127', atto: "chiocciola", obiettivi: [{ tipo: 'righe', quanti: 8 }], maxMosse: 26,
    griglia: MOTIVI.anello, },
  { numero: 128, nome: 'colonne128', atto: "chiocciola", obiettivi: [{ tipo: 'colonne', quanti: 7 }], maxMosse: 24,
    griglia: MOTIVI.gradini, },
  { numero: 129, nome: 'catena129', atto: "chiocciola", obiettivi: [{ tipo: 'catena', quanti: 3 }], maxMosse: 24,
    griglia: MOTIVI.spirale, },
  { numero: 130, nome: 'intrecci130', atto: "chiocciola", obiettivi: [{ tipo: 'intrecci', quanti: 1 }], maxMosse: 8,
    griglia: MOTIVI.pilastrini, },
  { numero: 131, nome: 'gruppi131', atto: "chiocciola", obiettivi: [{ tipo: 'gruppi', quanti: 8 }], maxMosse: 22,
    griglia: MOTIVI.anello, },
  { numero: 132, nome: 'quadranti132', atto: "chiocciola", obiettivi: [{ tipo: 'quadranti', quanti: 9 }], maxMosse: 26,
    griglia: MOTIVI.gradini, },
  { numero: 133, nome: 'righe133', atto: "chiocciola", obiettivi: [{ tipo: 'righe', quanti: 7 }], maxMosse: 21,
    griglia: MOTIVI.spirale, },
  { numero: 134, nome: 'colonne134', atto: "chiocciola", obiettivi: [{ tipo: 'colonne', quanti: 8 }], maxMosse: 26,
    griglia: MOTIVI.pilastrini, },
  { numero: 135, nome: 'catena135', atto: "chiocciola", obiettivi: [{ tipo: 'catena', quanti: 2 }], maxMosse: 12,
    griglia: MOTIVI.anello, },
  { numero: 136, nome: 'intrecci136', atto: "chiocciola", obiettivi: [{ tipo: 'intrecci', quanti: 2 }], maxMosse: 22,
    griglia: MOTIVI.gradini, },
  { numero: 137, nome: 'gruppi137', atto: "chiocciola", obiettivi: [{ tipo: 'gruppi', quanti: 12 }], maxMosse: 24,
    griglia: MOTIVI.spirale, },
  { numero: 138, nome: 'quadranti138', atto: "chiocciola", obiettivi: [{ tipo: 'quadranti', quanti: 8 }], maxMosse: 21,
    griglia: MOTIVI.pilastrini, },
  { numero: 139, nome: 'righe139', atto: "chiocciola", obiettivi: [{ tipo: 'righe', quanti: 8 }], maxMosse: 26,
    griglia: MOTIVI.anello, },
  { numero: 140, nome: 'colonne140', atto: "chiocciola", obiettivi: [{ tipo: 'colonne', quanti: 7 }], maxMosse: 21,
    griglia: MOTIVI.gradini, },
  { numero: 141, nome: 'catena141', atto: "feritoie", obiettivi: [{ tipo: 'catena', quanti: 3 }], maxMosse: 20,
    griglia: MOTIVI.feritoie, },
  { numero: 142, nome: 'intrecci142', atto: "feritoie", obiettivi: [{ tipo: 'intrecci', quanti: 3 }], maxMosse: 15,
    griglia: MOTIVI.torrette, },
  { numero: 143, nome: 'gruppi143', atto: "feritoie", obiettivi: [{ tipo: 'gruppi', quanti: 6 }], maxMosse: 19,
    griglia: MOTIVI.cuori, },
  { numero: 144, nome: 'quadranticatena144', atto: "feritoie", obiettivi: [{ tipo: 'quadranti', quanti: 5 }, { tipo: 'catena', quanti: 3 }], maxMosse: 16,
    griglia: MOTIVI.spirale, },
  { numero: 145, nome: 'punti145', atto: "feritoie", obiettivi: [{ tipo: 'punteggio', quanti: 250 }], maxMosse: 17,
    griglia: MOTIVI.pilastrini, },
  { numero: 146, nome: 'catena146', atto: "feritoie", obiettivi: [{ tipo: 'catena', quanti: 5 }], maxMosse: 23,
    griglia: MOTIVI.feritoie, },
  { numero: 147, nome: 'intrecci147', atto: "feritoie", obiettivi: [{ tipo: 'intrecci', quanti: 4 }], maxMosse: 24,
    griglia: MOTIVI.torrette, },
  { numero: 148, nome: 'gruppipunti148', atto: "feritoie", obiettivi: [{ tipo: 'gruppi', quanti: 3 }, { tipo: 'punteggio', quanti: 175 }], maxMosse: 18,
    griglia: MOTIVI.cuori, },
  { numero: 149, nome: 'quadranti149', atto: "feritoie", obiettivi: [{ tipo: 'quadranti', quanti: 9 }], maxMosse: 22,
    griglia: MOTIVI.spirale, },
  { numero: 150, nome: 'punti150', atto: "feritoie", obiettivi: [{ tipo: 'punteggio', quanti: 275 }], maxMosse: 23,
    griglia: MOTIVI.pilastrini, },
  { numero: 151, nome: 'catena151', atto: "feritoie", obiettivi: [{ tipo: 'catena', quanti: 3 }], maxMosse: 20,
    griglia: MOTIVI.feritoie, },
  { numero: 152, nome: 'intrecciquadranti152', atto: "feritoie", obiettivi: [{ tipo: 'intrecci', quanti: 1 }, { tipo: 'quadranti', quanti: 8 }], maxMosse: 24,
    griglia: MOTIVI.torrette, },
  { numero: 153, nome: 'gruppi153', atto: "feritoie", obiettivi: [{ tipo: 'gruppi', quanti: 6 }], maxMosse: 18,
    griglia: MOTIVI.cuori, },
  { numero: 154, nome: 'quadranti154', atto: "feritoie", obiettivi: [{ tipo: 'quadranti', quanti: 9 }], maxMosse: 23,
    griglia: MOTIVI.spirale, },
  { numero: 155, nome: 'punti155', atto: "feritoie", obiettivi: [{ tipo: 'punteggio', quanti: 235 }], maxMosse: 22,
    griglia: MOTIVI.pilastrini, },
  { numero: 156, nome: 'catenagruppi156', atto: "feritoie", obiettivi: [{ tipo: 'catena', quanti: 2 }, { tipo: 'gruppi', quanti: 4 }], maxMosse: 13,
    griglia: MOTIVI.feritoie, },
  { numero: 157, nome: 'intrecci157', atto: "feritoie", obiettivi: [{ tipo: 'intrecci', quanti: 4 }], maxMosse: 24,
    griglia: MOTIVI.torrette, },
  { numero: 158, nome: 'gruppi158', atto: "feritoie", obiettivi: [{ tipo: 'gruppi', quanti: 6 }], maxMosse: 21,
    griglia: MOTIVI.cuori, },
  { numero: 159, nome: 'punti159', atto: "loggia", obiettivi: [{ tipo: 'punteggio', quanti: 425 }], maxMosse: 26,
    griglia: MOTIVI.arcate, },
  { numero: 160, nome: 'catena160', atto: "loggia", obiettivi: [{ tipo: 'catena', quanti: 4 }], maxMosse: 20,
    griglia: MOTIVI.colonnato, },
  { numero: 161, nome: 'intrecci161', atto: "loggia", obiettivi: [{ tipo: 'intrecci', quanti: 6 }], maxMosse: 30,
    griglia: MOTIVI.torrette, },
  { numero: 162, nome: 'gruppirighe162', atto: "loggia", obiettivi: [{ tipo: 'gruppi', quanti: 10 }, { tipo: 'righe', quanti: 7 }], maxMosse: 27,
    griglia: MOTIVI.anello, },
  { numero: 163, nome: 'celle163', atto: "loggia", obiettivi: [{ tipo: 'celle', quanti: 66 }], maxMosse: 23,
    griglia: MOTIVI.gradini, },
  { numero: 164, nome: 'righe164', atto: "loggia", obiettivi: [{ tipo: 'righe', quanti: 9 }], maxMosse: 24,
    griglia: MOTIVI.arcate, },
  { numero: 165, nome: 'punti165', atto: "loggia", obiettivi: [{ tipo: 'punteggio', quanti: 450 }], maxMosse: 25,
    griglia: MOTIVI.colonnato, },
  { numero: 166, nome: 'catenacelle166', atto: "loggia", obiettivi: [{ tipo: 'catena', quanti: 8 }, { tipo: 'celle', quanti: 78 }], maxMosse: 23,
    griglia: MOTIVI.torrette, },
  { numero: 167, nome: 'intrecci167', atto: "loggia", obiettivi: [{ tipo: 'intrecci', quanti: 2 }], maxMosse: 24,
    griglia: MOTIVI.anello, },
  { numero: 168, nome: 'gruppi168', atto: "loggia", obiettivi: [{ tipo: 'gruppi', quanti: 8 }], maxMosse: 21,
    griglia: MOTIVI.gradini, },
  { numero: 169, nome: 'celle169', atto: "loggia", obiettivi: [{ tipo: 'celle', quanti: 90 }], maxMosse: 27,
    griglia: MOTIVI.arcate, },
  { numero: 170, nome: 'righecatena170', atto: "loggia", obiettivi: [{ tipo: 'righe', quanti: 2 }, { tipo: 'catena', quanti: 3 }], maxMosse: 20,
    griglia: MOTIVI.colonnato, },
  { numero: 171, nome: 'punti171', atto: "loggia", obiettivi: [{ tipo: 'punteggio', quanti: 675 }], maxMosse: 25,
    griglia: MOTIVI.torrette, },
  { numero: 172, nome: 'catena172', atto: "loggia", obiettivi: [{ tipo: 'catena', quanti: 5 }], maxMosse: 30,
    griglia: MOTIVI.anello, },
  { numero: 173, nome: 'intrecci173', atto: "loggia", obiettivi: [{ tipo: 'intrecci', quanti: 3 }], maxMosse: 23,
    griglia: MOTIVI.gradini, },
  { numero: 174, nome: 'gruppiintrecci174', atto: "loggia", obiettivi: [{ tipo: 'gruppi', quanti: 12 }, { tipo: 'intrecci', quanti: 3 }], maxMosse: 28,
    griglia: MOTIVI.arcate, },
  { numero: 175, nome: 'celle175', atto: "loggia", obiettivi: [{ tipo: 'celle', quanti: 77 }], maxMosse: 24,
    griglia: MOTIVI.colonnato, },
  { numero: 176, nome: 'righe176', atto: "loggia", obiettivi: [{ tipo: 'righe', quanti: 10 }], maxMosse: 25,
    griglia: MOTIVI.torrette, },
  { numero: 177, nome: 'punti177', atto: "merli", obiettivi: [{ tipo: 'punteggio', quanti: 700 }], maxMosse: 32,
    griglia: MOTIVI.crenellature, },
  { numero: 178, nome: 'catena178', atto: "merli", obiettivi: [{ tipo: 'catena', quanti: 7 }], maxMosse: 24,
    griglia: MOTIVI.fortezza, },
  { numero: 179, nome: 'celle179', atto: "merli", obiettivi: [{ tipo: 'celle', quanti: 77 }], maxMosse: 23,
    griglia: MOTIVI.arcate, },
  { numero: 180, nome: 'intreccipunti180', atto: "merli", obiettivi: [{ tipo: 'intrecci', quanti: 2 }, { tipo: 'punteggio', quanti: 175 }], maxMosse: 24,
    griglia: MOTIVI.feritoie, },
  { numero: 181, nome: 'colonne181', atto: "merli", obiettivi: [{ tipo: 'colonne', quanti: 8 }], maxMosse: 24,
    griglia: MOTIVI.colonnato, },
  { numero: 182, nome: 'gruppi182', atto: "merli", obiettivi: [{ tipo: 'gruppi', quanti: 13 }], maxMosse: 29,
    griglia: MOTIVI.crenellature, },
  { numero: 183, nome: 'punti183', atto: "merli", obiettivi: [{ tipo: 'punteggio', quanti: 700 }], maxMosse: 31,
    griglia: MOTIVI.fortezza, },
  { numero: 184, nome: 'catenaintrecci184', atto: "merli", obiettivi: [{ tipo: 'catena', quanti: 3 }, { tipo: 'intrecci', quanti: 3 }], maxMosse: 30,
    griglia: MOTIVI.arcate, },
  { numero: 185, nome: 'celle185', atto: "merli", obiettivi: [{ tipo: 'celle', quanti: 69 }], maxMosse: 23,
    griglia: MOTIVI.feritoie, },
  { numero: 186, nome: 'intrecci186', atto: "merli", obiettivi: [{ tipo: 'intrecci', quanti: 3 }], maxMosse: 27,
    griglia: MOTIVI.colonnato, },
  { numero: 187, nome: 'colonne187', atto: "merli", obiettivi: [{ tipo: 'colonne', quanti: 10 }], maxMosse: 32,
    griglia: MOTIVI.crenellature, },
  { numero: 188, nome: 'gruppicelle188', atto: "merli", obiettivi: [{ tipo: 'gruppi', quanti: 10 }, { tipo: 'celle', quanti: 69 }], maxMosse: 23,
    griglia: MOTIVI.fortezza, },
  { numero: 189, nome: 'punti189', atto: "merli", obiettivi: [{ tipo: 'punteggio', quanti: 650 }], maxMosse: 30,
    griglia: MOTIVI.arcate, },
  { numero: 190, nome: 'catena190', atto: "merli", obiettivi: [{ tipo: 'catena', quanti: 3 }], maxMosse: 13,
    griglia: MOTIVI.feritoie, },
  { numero: 191, nome: 'celle191', atto: "merli", obiettivi: [{ tipo: 'celle', quanti: 90 }], maxMosse: 24,
    griglia: MOTIVI.colonnato, },
  { numero: 192, nome: 'intreccicelle192', atto: "merli", obiettivi: [{ tipo: 'intrecci', quanti: 4 }, { tipo: 'celle', quanti: 96 }], maxMosse: 30,
    griglia: MOTIVI.crenellature, },
  { numero: 193, nome: 'punti193', atto: "vetta", obiettivi: [{ tipo: 'punteggio', quanti: 698 }], maxMosse: 32,
    griglia: MOTIVI.pinnacolo, },
  { numero: 194, nome: 'celle194', atto: "vetta", obiettivi: [{ tipo: 'celle', quanti: 117 }], maxMosse: 35,
    griglia: MOTIVI.assedioMassi, },
  { numero: 195, nome: 'catena195', atto: "vetta", obiettivi: [{ tipo: 'catena', quanti: 6 }], maxMosse: 26,
    griglia: MOTIVI.fortezza, },
  { numero: 196, nome: 'gruppiquadranti196', atto: "vetta", obiettivi: [{ tipo: 'gruppi', quanti: 16 }, { tipo: 'quadranti', quanti: 12 }], maxMosse: 34,
    griglia: MOTIVI.crenellature, },
  { numero: 197, nome: 'intrecci197', atto: "vetta", obiettivi: [{ tipo: 'intrecci', quanti: 4 }], maxMosse: 40,
    griglia: MOTIVI.pinnacolo, },
  { numero: 198, nome: 'quadranti198', atto: "vetta", obiettivi: [{ tipo: 'quadranti', quanti: 12 }], maxMosse: 28,
    griglia: MOTIVI.assedioMassi, },
  { numero: 199, nome: 'punti199', atto: "vetta", obiettivi: [{ tipo: 'punteggio', quanti: 1375 }], maxMosse: 38,
    griglia: MOTIVI.fortezza, },
  { numero: 200, nome: 'cellequadranti200', atto: "vetta", obiettivi: [{ tipo: 'celle', quanti: 81 }, { tipo: 'quadranti', quanti: 8 }], maxMosse: 26,
    griglia: MOTIVI.crenellature, },
];

/**
 * Gli atti dell'opera: servono a far vedere dove si e' arrivati.
 *
 * Qui c'e' l'IDENTIFICATIVO, non il nome. Il nome visibile sta nelle traduzioni, sotto
 * "atti.<id>": finche' e' stato scritto qui, in italiano, chi giocava in inglese leggeva
 * "Le basi" e "La vetta" dentro un'interfaccia inglese, e nessuno se n'era accorto perche'
 * i dati generati non passano da nessun controllo sulle traduzioni.
 */
export const ATTI = [
  {
    id: "basamento",
    da: 101,
    a: 110
  },
  {
    id: "mura",
    da: 111,
    a: 124
  },
  {
    id: "chiocciola",
    da: 125,
    a: 140
  },
  {
    id: "feritoie",
    da: 141,
    a: 158
  },
  {
    id: "loggia",
    da: 159,
    a: 176
  },
  {
    id: "merli",
    da: 177,
    a: 192
  },
  {
    id: "vetta",
    da: 193,
    a: 200
  }
];
